version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> laraxot/dev
      interval: "daily"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "npm"
      - "dependencies"
<<<<<<< HEAD
=======
=======
      interval: "weekly"
    labels:
      - "dependencies"
>>>>>>> 6e44b7d5 (.)
>>>>>>> laraxot/dev
