<<<<<<< HEAD
name: Update Changelog
=======
name: "Update Changelog"
>>>>>>> dfac49d (.)

on:
  release:
    types: [released]

<<<<<<< HEAD
=======
permissions:
  contents: write

>>>>>>> dfac49d (.)
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
<<<<<<< HEAD
        uses: actions/checkout@v7
=======
        uses: actions/checkout@v3
>>>>>>> dfac49d (.)
        with:
          ref: main

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated CHANGELOG
<<<<<<< HEAD
        uses: stefanzweifel/git-auto-commit-action@v5
=======
        uses: stefanzweifel/git-auto-commit-action@latest
>>>>>>> dfac49d (.)
        with:
          branch: main
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md
